apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: student-service
  name: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: student-service
    spec:
      containers:
      - image: apaspxp/student-service:latest
        name: student-service
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: student-service
  name: student-service
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: student-service
  type: ClusterIP
status:
  loadBalancer: {}
